apiVersion: v1
kind: Secret
metadata:
  name: projects-service-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  DB_ADMIN_PASSWORD: {{ .Values.secrets.dbAdminPassword | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  ENCRYPTION_KEY: {{ .Values.secrets.encryptionKey | quote }}
