apiVersion: v1
kind: Service
metadata:
  name: projects-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: projects-service
  ports:
    - port: {{ .Values.grpc.port }}
      targetPort: {{ .Values.grpc.port }}
